### ISSUE TITLE
Make file unsuccessful

### ISSUE THREAD

**Issue by NoFeeding** [toncenter/ton-index-worker#39]
Hi everyone I am new to this ton indexer GitHub. After following the steps I can have postgres and Indexer API container running on my server.
However, compiling worker never succeed so I am seeking help here. 
Below is my whole log after doing command: 

 cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=off -GNinja ..
 
For me from docker build, add2systemd script to build binary. All stuck here and somehow I think git clone cannot get required files to finish cmake. Hope can get some help soon. Thanks!

Add abseil-cpp
CMake Error at external/ton/CMakeLists.txt:120 (add_subdirectory):
  The source directory

    /home/ubuntu/ton-indexer/ton-index-worker/external/ton/third-party/abseil-cpp

  does not contain a CMakeLists.txt file.

Add crc32c
CMake Error at external/ton/CMakeLists.txt:143 (add_subdirectory):
  The source directory

    /home/ubuntu/ton-indexer/ton-index-worker/external/ton/third-party/crc32c

  does not contain a CMakeLists.txt file.

Add rocksdb
CMake Error at external/ton/CMakeLists.txt:160 (add_subdirectory):
  The source directory

    /home/ubuntu/ton-indexer/ton-index-worker/external/ton/third-party/rocksdb

  does not contain a CMakeLists.txt file.

Add ton
-- Found ccache
-- Could NOT find LATEX (missing: LATEX_COMPILER) 
-- Could NOT find LATEX (this is NOT an error)
-- Found ZLIB: /usr/include /usr/lib/x86_64-linux-gnu/libz.so
CMake Error at external/ton/CMakeLists.txt:388 (get_target_property):
  get_target_property() called with non-existent target
  "absl::flat_hash_map".
Call Stack (most recent call first):
  external/ton/tdutils/CMakeLists.txt:342 (target_link_libraries_system)

CMake Error at external/ton/CMakeLists.txt:388 (get_target_property):
  get_target_property() called with non-existent target
  "absl::flat_hash_set".
Call Stack (most recent call first):
  external/ton/tdutils/CMakeLists.txt:342 (target_link_libraries_system)

CMake Error at external/ton/CMakeLists.txt:388 (get_target_property):
  get_target_property() called with non-existent target "absl::hash".
Call Stack (most recent call first):
  external/ton/tdutils/CMakeLists.txt:342 (target_link_libraries_system)

-- Found Readline: /usr/include /usr/lib/x86_64-linux-gnu/libreadline.so
-- Found Secp256k1: /usr/lib/x86_64-linux-gnu/libsecp256k1.so
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Found MHD: /usr/lib/x86_64-linux-gnu/libmicrohttpd.so
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Generating config.h
-- Generating config.h - done
absl::int128 properties:
CMake Error at external/clickhouse-cpp/CMakeLists.txt:109 (get_target_property):
  get_target_property() called with non-existent target "absl::int128".
Call Stack (most recent call first):
  external/clickhouse-cpp/CMakeLists.txt:121 (print_target_properties)
  external/clickhouse-cpp/CMakeLists.txt:132 (print_target_debug_info)

	INCLUDE_DIRECTORIES : 
CMake Error at external/clickhouse-cpp/CMakeLists.txt:109 (get_target_property):
  get_target_property() called with non-existent target "absl::int128".
Call Stack (most recent call first):
  external/clickhouse-cpp/CMakeLists.txt:121 (print_target_properties)
  external/clickhouse-cpp/CMakeLists.txt:132 (print_target_debug_info)

	BINARY_DIR : 
CMake Error at external/clickhouse-cpp/CMakeLists.txt:109 (get_target_property):
  get_target_property() called with non-existent target "absl::int128".
Call Stack (most recent call first):
  external/clickhouse-cpp/CMakeLists.txt:121 (print_target_properties)
  external/clickhouse-cpp/CMakeLists.txt:132 (print_target_debug_info)

	INTERFACE_INCLUDE_DIRECTORIES : 
CMake Error at external/clickhouse-cpp/CMakeLists.txt:109 (get_target_property):
  get_target_property() called with non-existent target "absl::int128".
Call Stack (most recent call first):
  external/clickhouse-cpp/CMakeLists.txt:121 (print_target_properties)
  external/clickhouse-cpp/CMakeLists.txt:132 (print_target_debug_info)

	INTERFACE_LINK_LIBRARIES : 
CMake Error at external/clickhouse-cpp/CMakeLists.txt:109 (get_target_property):
  get_target_property() called with non-existent target "absl::int128".
Call Stack (most recent call first):
  external/clickhouse-cpp/CMakeLists.txt:121 (print_target_properties)
  external/clickhouse-cpp/CMakeLists.txt:132 (print_target_debug_info)

	LINK_LIBRARIES : 
CMake Error at external/clickhouse-cpp/CMakeLists.txt:109 (get_target_property):
  get_target_property() called with non-existent target "absl::int128".
Call Stack (most recent call first):
  external/clickhouse-cpp/CMakeLists.txt:121 (print_target_properties)
  external/clickhouse-cpp/CMakeLists.txt:132 (print_target_debug_info)

	LINK_LIBRARIES_ONLY_TARGETS : 
CMake Error at external/clickhouse-cpp/CMakeLists.txt:109 (get_target_property):
  get_target_property() called with non-existent target "absl::int128".
Call Stack (most recent call first):
  external/clickhouse-cpp/CMakeLists.txt:121 (print_target_properties)
  external/clickhouse-cpp/CMakeLists.txt:132 (print_target_debug_info)

	IMPORTED_LOCATION : 
cityhash::cityhash properties:
	INCLUDE_DIRECTORIES : /home/ubuntu/ton-indexer/ton-index-worker/external/clickhouse-cpp/contrib/lz4/lz4;/home/ubuntu/ton-indexer/ton-index-worker/external/clickhouse-cpp/contrib/cityhash/cityhash
	BINARY_DIR : /home/ubuntu/ton-indexer/ton-index-worker/build/external/clickhouse-cpp/contrib/cityhash/cityhash
	INTERFACE_INCLUDE_DIRECTORIES : PROPERTY-NOTFOUND
	INTERFACE_LINK_LIBRARIES : PROPERTY-NOTFOUND
	LINK_LIBRARIES : PROPERTY-NOTFOUND
	LINK_LIBRARIES_ONLY_TARGETS : PROPERTY-NOTFOUND
	IMPORTED_LOCATION : PROPERTY-NOTFOUND
lz4::lz4 properties:
	INCLUDE_DIRECTORIES : /home/ubuntu/ton-indexer/ton-index-worker/external/clickhouse-cpp/contrib/lz4/lz4
	BINARY_DIR : /home/ubuntu/ton-indexer/ton-index-worker/build/external/clickhouse-cpp/contrib/lz4/lz4
	INTERFACE_INCLUDE_DIRECTORIES : PROPERTY-NOTFOUND
	INTERFACE_LINK_LIBRARIES : PROPERTY-NOTFOUND
	LINK_LIBRARIES : PROPERTY-NOTFOUND
	LINK_LIBRARIES_ONLY_TARGETS : PROPERTY-NOTFOUND
	IMPORTED_LOCATION : PROPERTY-NOTFOUND
-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/ton-indexer/ton-index-worker/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/ton-indexer/ton-index-worker/build/CMakeFiles/CMakeError.log".

**Comment by dungeon-master-666** [comment]
Probably you did not pull submodules, try running `git submodule update --init --recursive`.

**Comment by NoFeeding** [comment]
Thank you the container is up now. Will gain more git knowledge from now on!
